import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrimaryColorProvider from "@/components/theme/primary-color-provider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { Spinner } from "@/components/ui/spinner";
import React from "react";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Working App",
  description: "Generated by Working App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-[#DBDBDB] dark:bg-[#12182a] max-h-screen overflow-hidden`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <React.Suspense fallback={<Spinner className="size-6" />}>
            {children}
          </React.Suspense>
          <PrimaryColorProvider />
          <Toaster richColors position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
