import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Working App",
  description: "Generated by Working App",
  manifest: "/manifest.webmanifest",
  themeColor: "#000000",
  appleWebApp: {
    capable: true,
    title: "Working Time",
    statusBarStyle: "default",
  },
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-[#DBDBDB] dark:bg-[#12182a] max-h-dvh overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
