import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrimaryColorProvider from "@/components/theme/primary-color-provider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Working App",
  description: "Generated by Working App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-[#DBDBDB]`}>
        {children}
        <PrimaryColorProvider />
      </body>
    </html>
  );
}
