/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrimaryColorProvider from "@/components/theme/primary-color-provider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { Spinner } from "@/components/ui/spinner";
import React from "react";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Working App",
  description: "Generated by Working App",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // ✅ NEXT.JS 16: params HARUS di-await
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-[#DBDBDB] dark:bg-[#12182a] max-h-screen overflow-hidden`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <React.Suspense fallback={<Spinner className="size-6" />}>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </React.Suspense>

          <PrimaryColorProvider />
          <Toaster richColors position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
